name: Quality code

on:
    workflow_dispatch

jobs:
    SonarQube:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Sstup Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Install dep
              run: npm i

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token utilisateur
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}